### PR TITLE
Fix `test_choi_to_kraus()` randomly crashing

### PR DESCRIPTION
**Pull request by renatomello**
Checklist:
- [ ] Reviewers confirm new code works as expected.
- [x] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.

### CODE REVIEW

**Comment by renatomello** [comment]
Since `choi_to_kraus()` depends on a spectral decomposition (or SVD), sometimes the numerical precision becomes 1-3% above `qibo.config.PRECISION_TOL`. Therefore, I increased precision for those tests and they should be fine now.

**Comment by renatomello** [comment]
This is ready for merge after review @AleCandido @andrea-pasquale

**Review by AleCandido — COMMENTED** [review]
Fine by me, but are you sure is it okay with increasing the tolerance by a factor of 10?

In particular, if raising tolerance is the chosen solution, a factor of 2 would have been sufficient.

**Comment by renatomello** [comment]
> Fine by me, but are you sure is it okay with increasing the tolerance by a factor of 10?
> 
> In particular, if raising tolerance is the chosen solution, a factor of 2 would have been sufficient.

Changed it.

**Review by andrea-pasquale — APPROVED** [review]
Thanks @renatomello.

**Pull request merged**
