### PR TITLE
Fix math rendering in some docsstrings of the `quantum_info` module

### PR DESCRIPTION
**Pull request by renatomello**
Checklist:
- [x] Reviewers confirm new code works as expected.
- [x] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.

### CODE REVIEW

**Review by MatteoRobbiati — APPROVED** [review]
Thanks, I confirm now it renders properly.

**Review by MatteoRobbiati — APPROVED** [review]
Thanks! Is the choice of the notation $|v)$ common? Just curiosity :)

**Comment by renatomello** [comment]
> Thanks! Is the choice of the notation | v ) common? Just curiosity :)

yes, either that or double kets like `|A>>``

**Comment by alecandido** [comment]
> yes, either that or double kets like | A ⟩⟩

I also seen the double kets somewhere in the docs. Should we keep just one or the other?

**Comment by renatomello** [comment]
> > yes, either that or double kets like | A ⟩⟩
> 
> I've also seen the double kets somewhere in the docs. Should we keep just one or the other?

Done

**Review by BrunoLiegiBastonLiegi — APPROVED** [review]

**Comment by alecandido** [comment]
> Done

Thanks @renatomello!

**Pull request merged**
