### PR TITLE
Dbi transpiling code structure

### PR DESCRIPTION
**Pull request by marekgluza**
This PR delivers a workeable structure for further development.
The point is to:
- show you the idea of the DBI transpiling
- ask you for your opinion for the design structure
- if you agree then to ask one of you to take it over and combine this with Circuit gate counting techniques
- the next 2 weeks I will not be able to work on this so let's make plans on matrix how to move ahead with gate counting 

More specifically
- there are 2 new files in /dbi
- the goal was to propose a workflow which is capable of explaininig how the DBI transpiling into circuits must work (see  overleaf for the revision of my paper)
- the idea is that there is now a class EvolutionOracle  that can be working underneath with Circuit or numpy. Numpy we have in double_bracket.py so it's backwards compatible and Circuit e.g. for counting gates
- then there is the group commutator iteration file which is showing how to run the oracles. For the transpiling the key idea is the class FrameShiftedEvolutionOracle which recursively implements
$$e^{it H_k} = e^{itU^\dagger H_0 U} = U^\dagger e^{itH_0} U$$
which is what I refer to as frame shifting
- using that we have the evolution oracle of the iterated input hamiltonian so we know how to relate the group commutator step to
$$V = e^{is D_k}e^{isH_k}e^{-is D_k}e^{-isH_k}$$
  the $H_0$ evolution
$$V = e^{is D_k}U^\dagger e^{itH_0} Ue^{-is D_k}U^\dagger e^{-itH_0} U$$

Checklist:
- [ ] Reviewers confirm new code structure is reasonable.

### CODE REVIEW

**Comment by scarrazza** [comment]
@marekgluza thanks for this but could you please move the discussion points in a new issue referring to this PR, so we can interact there? Thank you.

**Comment by marekgluza** [comment]
@scarrazza  done

@MatteoRobbiati I think it's working ok now. There is a full integration with SymbolicHamiltonian.circuit to my knowledge and I'm getting some numbers out which make sense

I'd recommend to merge into the root class if you are fine with the code structure and then we develop the code further?

**Comment by marekgluza** [comment]
I merged some more work on the classess:
- [x] you can now __call__ the new group commutator iterations with oracles and recursively get a circuit that matches what we had in the basic double_bracket.py

**Comment by Edoardo-Pedicillo** [comment]
@marekgluza is the PR ready for review (some tests are not passing)?

**Comment by marekgluza** [comment]
Hi Edoardo, the PR was meant only to show you the code structure. I will merge it with the main transpiling branch next time I will be adding to this code.

If you have some feedback about orgnizing the code then I'd be happy to hear. We can also discuss tomorrow over zoom :)

**Pull request closed without merging**
