### PR TITLE
Nix

### PR DESCRIPTION
**Pull request by AleCandido**
Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

### CODE REVIEW

**Review by scarrazza — APPROVED** [review]

**Comment by scarrazza** [comment]
@AleCandido why nix in the lock file? Could you please fix the conflict, it seems that I cannot simply do `poetry update`?

**Comment by AleCandido** [comment]
Nix has its own lock file, `flake.lock`, and it's completely decoupled. The conflict comes from this branch being based on an old version of `master`, and the lock file having been modified in #809 (I added IPython and pdb++ as development tools).

I reran `poetry lock`, and everything should be fixed and consistent

**Comment by scarrazza** [comment]
Thanks, we can merge as soon as tests pass.

**Comment by scarrazza** [comment]
Windows seems not happy again.

**Comment by AleCandido** [comment]
The problem doesn't seem to be Windows, but rather a conflict with #1039.

It actually defined `M.load` in a separate way from any other gate, and now it is conflicting with the general `Gate.load`, and failing in `test_result.py`.

**Comment by scarrazza** [comment]
@BrunoLiegiBastonLiegi could you please have a look and chat with @AleCandido

**Pull request merged**
