### PR TITLE
Raise error if QAOA Hamiltonians have different nqubits

### PR DESCRIPTION
**Pull request by stavros11**
Temporary fix for #558 until we make the model more flexible to allow applying operators of different sizes.

### CODE REVIEW

**Comment by DiegoGM91** [comment]
Thanks for implementing this.

I just had a look and looks good to me. The only doubt I have is whether we should raise a `ValueError` or a `NotImplementedError`.

**Comment by stavros11** [comment]
> I just had a look and looks good to me. The only doubt I have is whether we should raise a `ValueError` or a `NotImplementedError`.

Thank you for the review. I am fine either way, given that we plan to implement this feature. Let's see if someone else has a preference.

**Review by scarrazza — APPROVED** [review]
Thanks, I think ValueError matches the specific check we perform.

**Review by andrea-pasquale — APPROVED** [review]
Thanks for the implementation.
I also agree with `ValueError`.

**Pull request merged**
