### PR TITLE
removing print from parallel.py

### PR DESCRIPTION
**Pull request by scarrazza**
Fix issues spotted in #465.

### CODE REVIEW

**Comment by mlazzarin** [comment]
I'm afraid I cannot review this PR because I don't know how the whole parallel code works (yet).
However, I think it might introduce some subtle changes in the behavior of the code, because:
- raise_error now raises an additional exception w.r.t. print
- if I manually raise an error in the `try` body, now the tests `src/qibo/tests/test_parallel.py` get stuck forever, while with print they still work.

A comment hints to a specific reason for the usage of print. However I don't know ``multiprocessing`` well nor what the excepted behavior should be.

**Comment by scarrazza** [comment]
Indeed, the exceptions and logs doesn't work well on a multiprocessing environment, thus the `print` status is the simplest think we can have in order to get some information about the exception.

I think the situation still complex if we decide to log from multiple threads in python.
So we may prefer to include an exclusion filter in #465, and skipping the check for this particular `print` statement.

**Comment by mlazzarin** [comment]
> So we may prefer to include an exclusion filter in #465, and skipping the check for this particular `print` statement.

Ok, I'm on it.

**Comment by scarrazza** [comment]
Ok, I am closing this in favour of #465.

**Pull request closed without merging**
