### PR TITLE
Updating docs

### PR DESCRIPTION
**Pull request by scarrazza**
Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

### CODE REVIEW

**Comment by scarrazza** [comment]
@MatteoRobbiati could you please redo the diagrams in the getting started section?

**Review by Edoardo-Pedicillo — APPROVED** [review]

**Comment by scarrazza** [comment]
@MatteoRobbiati just a reminder, the two figures are located in:
- https://qibo.science/qibo/stable/getting-started/overview.html
- https://qibo.science/qibo/stable/getting-started/backends.html

**Comment by MatteoRobbiati** [comment]
Done @scarrazza. 
The `*.svg` format had a bug, when I fix it, I will upload those version. 
Do you think it can be useful to create a repo to collect all the XMind files? And, at this point, we can also delete the `tutorials` one if it is not needed.

**Comment by scarrazza** [comment]
Thanks @MatteoRobbiati looks good. If you manage please upload the svg also for the figure in the frontpage.

>  Do you think it can be useful to create a repo to collect all the XMind files? And, at this point, we can also delete the tutorials one if it is not needed.

Yes, please.

**Pull request merged**
