### PR TITLE
Choi representation of channels + transformations between representations

### PR DESCRIPTION
**Pull request by renatomello**
Checklist:
- [x] Reviewers confirm new code works as expected.
- [x] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.

### CODE REVIEW

**Comment by renatomello** [comment]
This closes #764

**Comment by renatomello** [comment]
As mentioned in the meeting, this closes items 3-6 raised by @vodovozovaliza on issue #765. So we agreed it'd be best to close issue #765 as well, and later we`ll open an issue that relates solely to the implementation of a master equation solver.

**Comment by renatomello** [comment]
This is ready for review.

**Comment by renatomello** [comment]
Converting back to draft to fix a bug noticed by @vodovozovaliza

**Review by vodovozovaliza — APPROVED** [review]

**Review by andrea-pasquale — COMMENTED** [review]
Thanks for implementing this @renatomello.
This PR looks good to me.
I'm not familiar with some of the operators introduced in this PR, I suggest to add somewhere either short latex block or a reference to a paper (similar to what Qiskit is doing [here](https://qiskit.org/documentation/stubs/qiskit.quantum_info.Choi.html) for the Choi channel. 

Let me know if you agree.

**Comment by renatomello** [comment]
> Thanks for implementing this @renatomello. This PR looks good to me. I'm not familiar with some of the operators introduced in this PR, I suggest to add somewhere either short latex block or a reference to a paper (similar to what Qiskit is doing [here](https://qiskit.org/documentation/stubs/qiskit.quantum_info.Choi.html) for the Choi channel).
> 
> Let me know if you agree.

Implemented.

**Comment by andrea-pasquale** [comment]
@renatomello I think that when you merged this PR tests were not passing.
In fact they are still failing even for new PR (for example #795).
Could you have a look when you have time?

**Comment by renatomello** [comment]
> @renatomello I think that when you merged this PR tests were not passing. In fact they are still failing even for new PRs (for example #795). Could you have a look when you have time?

Fix in #797

**Pull request merged**
