### PR TITLE
Fix `tensorflow` warnings in documentation examples

### LINKED ISSUE #897: Over 10k `tensorflow` warnings while testing documentation examples on Github
As I showed @stavros11 in person, there is one or more documentation examples that lead to over 10 thousand warnings due to `tensorflow` trying to cast `complex128` to `float64`. Due to the amount of warnings, this is probably happening inside an optimization, but there is no reference to which example(s) raise the warnings. I could not reproduce the warnings locally.

### PR DESCRIPTION
**Pull request by renatomello**
This closes #897 

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [x] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.

### CODE REVIEW

**Comment by renatomello** [comment]
@MatteoRobbiati the main problem was in the `qgain.train` method, but also another one in the examples. Fixed both.

**Comment by renatomello** [comment]
@MatteoRobbiati @Edoardo-Pedicillo this is ready for review

**Review by MatteoRobbiati — APPROVED** [review]
Thank you for this.

**Review by Edoardo-Pedicillo — APPROVED** [review]
Thank @renatomello

**Pull request merged**
