### PR TITLE
Add derivative to qibo docs

### PR DESCRIPTION
**Pull request by MatteoRobbiati**
in this PR, the description of the `derivative` module has been added to the documentation.

### CODE REVIEW

**Review by stavros11 — COMMENTED** [review]
Looks good. I would suggest to merge #735 here and fix the doctest so that we can merge.

**Comment by MatteoRobbiati** [comment]
I have just modified the module following your suggestions @stavros11. 
Thank you for the review.

**Comment by scarrazza** [comment]
@MatteoRobbiati looks good to me, however there is a documentation test failing, i.e. you have introduced a short code example in the documentation and when executed there is something that raises an error, could you please check so we can proceed with the merge?

**Comment by MatteoRobbiati** [comment]
> @MatteoRobbiati looks good to me, however there is a documentation test failing, i.e. you have introduced a short code example in the documentation and when executed there is something that raises an error, could you please check so we can proceed with the merge?

I think the problem is now solved.

**Pull request merged**
