### PR TITLE
adding qibojit to CI

### PR DESCRIPTION
**Pull request by scarrazza**

### CODE REVIEW

**Comment by stavros11** [comment]
Thanks for adding qibojit in CI. With this enabled we can now remove some `# pylint: disable` statements from the code that we used when qibojit was missing and re-enable coverage for the JIT backend. Shall I do this here?

**Comment by scarrazza** [comment]
Sure, but lets first merge #438 if you agree with these changes.

**Comment by stavros11** [comment]
I just noticed that qibojit is not installed and tested on Windows. I think in the docs we say that qibojit is supported on Windows so shouldn't we enable these tests?

**Comment by scarrazza** [comment]
@stavros11 thanks for pointing this out.

**Pull request merged**
