### PR TITLE
use diagonal matrix with group commutator

### PR DESCRIPTION
**Pull request by Edoardo-Pedicillo**
Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

### CODE REVIEW

**Review by andrea-pasquale — APPROVED** [review]

**Review by MatteoRobbiati — APPROVED** [review]
Thanks.
The tests errors are due to the `dbf_migrate` branch, right?

**Comment by andrea-pasquale** [comment]
> Thanks. The tests errors are due to the `dbf_migrate` branch, right?

Not really, I think that it is better if we fix them in this PR. @Edoardo-Pedicillo feel free to do it whenever you have time otherwise I can do it.

**Comment by Sam-XiaoyueLi** [comment]
@MatteoRobbiati  Hi Matteo, I think this PR broke `test_models_dbi.py` by removing the line `raise_error(ValueError, f"Cannot use group_commutator with matrix {d}")`. I'm not sure if we should update the test to reflect the changes or should I try to fix it in my branch (or this?). Please advise. Thanks!

/cc @Edoardo-Pedicillo  @andrea-pasquale

**Comment by MatteoRobbiati** [comment]
@Sam-XiaoyueLi you are right, because now we don't need to raise an error, since we have a default matrix `d`. I guess the solution is to remove the lines:

```python
    with pytest.raises(ValueError):
        dbf(mode=DoubleBracketGeneratorType.single_commutator, step=0.01)
```

from the tests. 

What do you think @Edoardo-Pedicillo, @andrea-pasquale?

**Comment by marekgluza** [comment]
> @Sam-XiaoyueLi you are right, because now we don't need to raise an error, since we have a default matrix `d`. I guess the solution is to remove the lines:
> 
> ```python
>     with pytest.raises(ValueError):
>         dbf(mode=DoubleBracketGeneratorType.single_commutator, step=0.01)
> ```
> 
> from the tests.
> 
> What do you think @Edoardo-Pedicillo, @andrea-pasquale?

@Sam-XiaoyueLi One comment, maybe others can help to understand the dependancies: I believe `d` is a numpy array, shouldn't it be `Hamiltonian`? That way other backends eg hardware won't have an issue?

For now DBI is not deployable because we don't unfold so it's a classical simulator model but I'm preparing to do the transpiler into Hamiltonian simulation and then we will have to switch. 

Possible solution: add `transpiled_double_bracket.py` which inherits and works with appropriate evolution oracles which here would derive from `Circuit`

**Comment by andrea-pasquale** [comment]
> @Sam-XiaoyueLi you are right, because now we don't need to raise an error, since we have a default matrix `d`. I guess the solution is to remove the lines:
> 
> ```python
>     with pytest.raises(ValueError):
>         dbf(mode=DoubleBracketGeneratorType.single_commutator, step=0.01)
> ```
> 
> from the tests.
> 
> What do you think @Edoardo-Pedicillo, @andrea-pasquale?

Hi all, indeed if we remove the lines that @MatteoRobbiati pointed out tests should pass. 
Basically this PR makes the `d` argument optional for `DoubleBracketGeneratorType.single_commutator` and if not provided it will use the diagonal part of the current Hamiltonian.
The fix needs to be performed in your branch @Sam-XiaoyueLi, I can take care of it.

**Pull request merged**
