### PR TITLE
Adding code of conduct

### PR DESCRIPTION
**Pull request by scarrazza**
Including a code of conduct before elaborating the contributing guidelines.

### CODE REVIEW

**Review by andrea-pasquale — APPROVED** [review]
Thanks @scarrazza, LGTM.
For contributors shall we add also a `CONTRIBUTING.md`?

**Comment by alecandido** [comment]
https://github.com/EthicalSource/contributor_covenant/blob/release/README.md#registering-your-community-as-an-adopter
?

**Comment by scarrazza** [comment]
@andrea-pasquale I will open another PR for that. @alecandido I will have a look. Are you suggesting to use that instead as template?

**Comment by alecandido** [comment]
> @alecandido I will have a look. Are you suggesting to use that instead as template?

Nono, that's exactly the template you used. I just took a look at the website, and they were suggesting to list yourself in their adopters. Not sure we want to go through the burden (i.e. just a PR adding a line to a CSV), but I posted just in case.

**Pull request merged**
