### PR TITLE
Bugfix to ``MeasurementOutcomes``

### LINKED ISSUE #1094: measurement.result not working for final measurements when intermediate measurements are present
When executing a circuit with intermediate measurements it is not possible to get the final measurement results directly from the measurement gate

```python
from qibo import gates
from qibo.models import Circuit
measurement = gates.M(0)
measurement2 = gates.M(0,1,2)

circ = Circuit(3, density_matrix=True)
circ.add(gates.H(0))
circ.add(measurement)
circ.add(gates.CNOT(0,1))
circ.add(measurement2)

original_result = circ.execute(nshots=100)
print(original_result.frequencies())
print(measurement2.result.frequencies())

Expected to get the same result for measurement2.result.frequencies() as original_result.frequencies()
I Get the following error:
Traceback (most recent call last):
  File "/home/simonebordoni/QIBO/qibo/src/qibo/transpiler/test_m.py", line 23, in <module>
    print(measurement2.result.frequencies())
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simonebordoni/QIBO/qibo/src/qibo/measurements.py", line 189, in frequencies
    self.samples(binary=False)
  File "/home/simonebordoni/QIBO/qibo/src/qibo/measurements.py", line 167, in samples
    return self.backend.samples_to_decimal(self._samples, len(qubits))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/simonebordoni/QIBO/qibo/src/qibo/backends/numpy.py", line 639, in samples_to_decimal
    return self.np.matmul(samples, qrange)[:, 0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: matmul: Input operand 0 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)
```

The error disappears if i remove the intermediate measurement gate. Everything also works fine if i try to recover the result of intermediate measurements:
```python
original_result = circ.execute(nshots=100)
print(original_result.frequencies())
print(measurement.result.frequencies())
```

### PR DESCRIPTION
**Pull request by BrunoLiegiBastonLiegi**
Small patch that fixes #1094. The `MeasurementOutcomes` object needs to register the samples into the measurements when it's built from samples.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

### CODE REVIEW

**Comment by BrunoLiegiBastonLiegi** [comment]
The ``test_circuit_add_sampling`` test inside ``test_models_circuit_noise.py`` is randomly failing for all the backends.

```
def test_circuit_add_sampling(backend):
    """Check measurements when simulating added circuits with noise"""
    # Create random noisy circuit and add noiseless inverted circuit
    gates_set = [gates.X, gates.Y, gates.Z, gates.H, gates.S, gates.SDG, gates.I]
    circ = Circuit(1)
    circ_no_noise = Circuit(1)

    for _ in range(10):
        new_gate = np.random.choice(gates_set)(0)
        circ.add(gates.PauliNoiseChannel(0, [("Z", 0.01)]))
        circ.add(new_gate)
        circ_no_noise.add(new_gate)

    circ.add(gates.PauliNoiseChannel(0, [("Z", 0.01)]))
    circ += circ_no_noise.invert()
    circ.add(gates.M(0))

    # Sampling using 10 shots
    np.random.seed(123)
    backend.set_seed(123)
    samples = backend.execute_circuit(circ, nshots=10).samples()
    
    # Sampling using 1 shot in for loop
    target_samples = []
    backend.set_seed(123)
    np.random.seed(123)
    for _ in range(10):
        result = backend.execute_circuit(circ, nshots=1)
        target_samples.append(result.samples())

    target_samples = np.stack(target_samples)
    
    backend.assert_allclose(samples, target_samples[:, 0])
```
I believe this might be related to the seed that in some cases is not set properly, for reason that are unclear to me. Still it's not very clear to me what is being tested here.

**Comment by renatomello** [comment]
@BrunoLiegiBastonLiegi I ran the minimal code @Simone-Bordoni mentioned in #1094 and the error seem to still occur.

**Comment by BrunoLiegiBastonLiegi** [comment]
> @BrunoLiegiBastonLiegi I ran the minimal code @Simone-Bordoni mentioned in #1094 and the error seem to still occur.

strange, it works for me locally

**Comment by renatomello** [comment]
> > @BrunoLiegiBastonLiegi I ran the minimal code @Simone-Bordoni mentioned in #1094 and the error seem to still occur.
> 
> strange, it works for me locally
> 
> EDIT: the merge of the master branch broke this for me

That is weird because the merging didn't revert back your changes. Can you check what happened?

**Review by stavros11 — APPROVED** [review]

**Review by renatomello — APPROVED** [review]

**Pull request merged**
