### PR TITLE
add iswap gate

### PR DESCRIPTION
**Pull request by Simone-Bordoni**
Checklist:
- [ ] Reviewers confirm new code works as expected.
- [X] Tests are passing.
- [X] Coverage does not decrease.
- [X] Documentation is updated.

### CODE REVIEW

**Comment by Simone-Bordoni** [comment]
I don't know if other parts must be edited

**Comment by scarrazza** [comment]
@Simone-Bordoni thank you, looks good. The only missing feature is the circuit.draw symbol plot definition.

**Comment by scarrazza** [comment]
In particular here: https://github.com/qiboteam/qibo/blob/7b9ca94bbe3919177fdda08433ccaf219184e25e/src/qibo/gates/gates.py#L7

**Comment by Simone-Bordoni** [comment]
I have added these parts, for now i have used "i" simbol for the circuit.draw()

**Review by stavros11 — APPROVED** [review]
Looks good to me, thanks.

**Pull request merged**
