### PR TITLE
Double bracket iterations

### PR DESCRIPTION
**Pull request by Edoardo-Pedicillo**
This PR implements a DoubleBracket class and solves #1034.

### TODO
- [ ] Implement features 2 and 3 of Marek's issue
- [x] Add examples with plotting functions under `examples` @MatteoRobbiati
- [x] Compute energy @Edoardo-Pedicillo 
- [x] Compute energy fluctuations @Edoardo-Pedicillo 
- [x] Find minimization flow step (gradient descent) @MatteoRobbiati
- [x] GPU acceleration @andrea-pasquale 

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [x] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.

### CODE REVIEW

**Comment by Edoardo-Pedicillo** [comment]
A small working example is provided in the documentation, now the algorithm does not converge because the step is not optimized. 

@scarrazza now the `DoubleBracket` class is in `qibo/hamiltonians` folder, let me know if I should move it in `qibo/models`

**Comment by scarrazza** [comment]
Thanks @, I agree with @MatteoRobbiati , better to move in models. Could you please proceed and include some basic tests?

**Comment by andrea-pasquale** [comment]
I've moved the class to `models` and I've also added a few minimal tests.
I've tested the implementation on all CPU backends and it seems to be working, I need to check if on GPU everything is working correctly.
Feel free to review/add suggestions :)
Here is a quick example:
```py
from qibo.models.double_bracket import DoubleBracketFlow, DoubleBracketFlowMode
from qibo import set_backend
import numpy as np
from qibo.hamiltonians.hamiltonians import Hamiltonian
from qibo.quantum_info import random_hermitian
import matplotlib.pyplot as plt

set_backend("numpy")

NSTEPS=100
nqubits = 4
h0 = random_hermitian(2**nqubits)

# define DBF
dbf = DoubleBracketFlow(Hamiltonian(nqubits=nqubits, matrix=h0))
for i in range(NSTEPS):
    # evolution under canonical commutator
    dbf(0.01, DoubleBracketFlowMode.canonical)

# plot matrix
plt.imshow(np.absolute(dbf.h.matrix), cmap='hot', interpolation='nearest')
```
download

I will proceed with the TODOs.

**Comment by marekgluza** [comment]
@Edoardo-Pedicillo @andrea-pasquale 
I commented a review of the DBI conventions change by @MatteoRobbiati  and suggested that the enum generator type will better be called `DoubleBracketGeneratorType` and not `IterationGeneratorType` which makes sense in the DBI context but will surely confuse somebody working elsewhere in QIBO if it shows up as an available class


 @Sam-XiaoyueLi we will discuss on Monday that we will be adding the routines as suggested in the issue by @shangtai  into a secondary file `additional_double_bracket_functions.py` next to `double_ bracket.py` as in  [2075cad](https://github.com/qiboteam/qibo/pull/1047/commits/2075cadeba7b7593437a3c06335313e3a6026297)

Sam, I'll ask you to migrate from the old repo the 
- regular 'flow' using the canonical bracket and let's call it `GWWDoubleBracketIteration` or `canonicalDoubleBracketIteration`, you choose unless somebody voices some preference. GWW flow is historicall based on the paper by Głazek and Wilson, and independently the paper by Wegner. Canonical is based on the book by Kehrein who calls that bracket canonical, this makes sense for us because of the double-bracket rotation formula
 $$||\sigma(e^{sW} H e^{- s W} )||- ||\sigma (H )||= s \langle W,M\rangle+O(s^2)$$
so the canonical bracket $M = [\Delta(H),\sigma(H)]= [H,\sigma(H)]= [\Delta(H),H]$ appears on its own.
- the multi qubit Pauli Z generator with $Z(\mu) = (Z_1)^{\mu_1}\ldots (Z_L)^{\mu_L}$ where we optimize over all binary strings $\mu\in \{0,1\}^L$ 
- the magnetic field $D = \sum_i B_i Z_i$
- the two qubit Ising model $D  = \sum_i B_i Z_i + \sum_{i,j} J_{i,j} Z_i Z_j$, please follow the tutorial by Matteo and use the QIBO ising model for that with $h=0$

After the meeting on Tuesday, we will discuss with Matteo how to do the gradients similarly to @wrightjandrew

**Comment by andrea-pasquale** [comment]
> @Edoardo-Pedicillo @andrea-pasquale
> I commented a review of the DBI conventions change by @MatteoRobbiati and suggested that the enum generator type will better be called `DoubleBracketGeneratorType` and not `IterationGeneratorType` which makes sense in the DBI context but will surely confuse somebody working elsewhere in QIBO if it shows up as an available class

Thanks @marekgluza for the feedback.
I just changed `IterationGeneratorType` to `DoubleBracketGeneratorType`  as you suggested.

**Comment by MatteoRobbiati** [comment]
> @Edoardo-Pedicillo @andrea-pasquale I commented a review of the DBI conventions change by @MatteoRobbiati and suggested that the enum generator type will better be called `DoubleBracketGeneratorType` and not `IterationGeneratorType` which makes sense in the DBI context but will surely confuse somebody working elsewhere in QIBO if it shows up as an available class

Thanks @marekgluza for the feedback, it is a good idea. And thanks @andrea-pasquale for the fast fix.

**Comment by Edoardo-Pedicillo** [comment]
@Sam-XiaoyueLi could you move your commit in a new branch and open a PR pointing to `dbf` branch ?
Look here
https://stackoverflow.com/questions/1628563/move-the-most-recent-commits-to-a-new-branch-with-git#:~:text=Moving%20to%20a,branch%2C%20e.g%3A (instead of `master` you have to use `dbf`).

**Review by andrea-pasquale — APPROVED** [review]

**Review by MatteoRobbiati — APPROVED** [review]

**Comment by marekgluza** [comment]
For currently the first checkbox the point number 3 which is Hamiltonian simulation from primitive gates in #1034 can now be linked with #1138 for a more detailed discussion. @Edoardo-Pedicillo, can you split the box first checkbox and for the 3rd point link the issue #1138 and tag @shangtai?

I will write a more detailed description of point number 2 in #1034 which is about transpiling DBIs. This will be in two stages DBI - > Hamiltonian simulation and Hamiltonian simulation -> primitive gates

**Pull request merged**
