### PR TITLE
Fix `apply_channel()` for statevector simulation

### LINKED ISSUE #1018: `DepolarizingChannel` gives wrong probabilities when used with state vectors
**Describe the bug**

The `DepolarizingChannel` with `lam=1` on a single qubit should give 0.5 probability for both 0 and 1 but gives 0.6 - 0.4.
The problem does not appear when using density matrices.

**To Reproduce**
```py
from qibo import Circuit, gates

nqubits = 1
qc = Circuit(nqubits)
lam = 1

qc.add(gates.DepolarizingChannel([0,], lam))
qc.add(gates.M(0))

# Execute circuit
result = qc.execute(nshots=10000)
counts = dict(result.frequencies(binary=True))
print(counts)
```

**Expected behavior**
Gives `{'0': 6316, '1': 3684}`. 

When using `qc = Circuit(nqubits, density_matrix=True)` it gives `{'0': 5035, '1': 4965}` which is more right.

### PR DESCRIPTION
**Pull request by AlejandroSopena**
This PR fixes #1018 . There was an error in the way we were sampling the gates to apply when using the  `apply_channel()` method. This also affects the `PauliNoiseChannel` and the `UnitaryChannel`.
We did not notice earlier because the tests are also not implemented correctly. I will fix them as soon as possible.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [x] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.

### CODE REVIEW

**Review by stavros11 — APPROVED** [review]
Thank you very much for the very quick fix @AlejandroSopena. Indeed, the previous implementation of `apply_channel` was not right.

Another test that we could do to find this bug earlier is to compare the shots or final probability distribution found with statevector simulation with the ones found using density matrix simulation, since the latter is deterministic (does not use random sampling) even when using channels. I did the following check to verify this PR:
```py
from qibo import Circuit, gates
from qibo.quantum_info.random_ensembles import random_unitary

matrix1 = random_unitary(2)
matrix2 = random_unitary(4)

c1 = Circuit(2, density_matrix=True)
c1.add(gates.UnitaryChannel([(0,), (0, 1)], [(0.1, matrix1), (0.2, matrix2)]))
c1.add(gates.M(0))

c2 = Circuit(2)
c2.add(gates.UnitaryChannel([(0,), (0, 1)], [(0.1, matrix1), (0.2, matrix2)]))
c2.add(gates.M(0))

result = c1(nshots=10000)
print(result.frequencies(binary=True))
result = c2(nshots=10000)
print(result.frequencies(binary=True))
```
The final frequencies differ slightly so we would need a tolerance if we convert this to a test.

Anyway, this PR is fine for me as it is.

**Comment by renatomello** [comment]
> Thank you very much for the very quick fix @AlejandroSopena. Indeed, the previous implementation of `apply_channel` was not right.
> 
> Another test that we could do to find this bug earlier is to compare the shots or final probability distribution found with statevector simulation with the ones found using density matrix simulation, since the latter is deterministic (does not use random sampling) even when using channels. I did the following check to verify this PR:
> 
> ```python
> from qibo import Circuit, gates
> from qibo.quantum_info.random_ensembles import random_unitary
> 
> matrix1 = random_unitary(2)
> matrix2 = random_unitary(4)
> 
> c1 = Circuit(2, density_matrix=True)
> c1.add(gates.UnitaryChannel([(0,), (0, 1)], [(0.1, matrix1), (0.2, matrix2)]))
> c1.add(gates.M(0, 1))
> 
> c2 = Circuit(2)
> c2.add(gates.UnitaryChannel([(0,), (0, 1)], [(0.1, matrix1), (0.2, matrix2)]))
> c2.add(gates.M(0, 1))
> 
> result = c1(nshots=10000)
> print(result.frequencies(binary=True))
> result = c2(nshots=10000)
> print(result.frequencies(binary=True))
> ```
> 
> The final frequencies differ slightly so we would need a tolerance if we convert this to a test.
> 
> Anyway, this PR is fine for me as it is.

This is the most appropriate way of testing this. So I'm  gonna add this test.

**Comment by scarrazza** [comment]
@renatomello thanks, are you planning to do this here? I am just asking because we would like to include this bug fix in the next release.

**Comment by renatomello** [comment]
> @renatomello thanks, are you planning to do this here? I am just asking because we would like to include this bug fix in the next release.

already working on it, I'll be done soon

**Comment by AlejandroSopena** [comment]
Thanks @stavros11, @renatomello. I also think this the best way to test this.

**Review by renatomello — APPROVED** [review]

**Review by stavros11 — APPROVED** [review]
Thanks for adding the test @renatomello. The issue with switching `circuit.density_matrix` after adding gates should be fixed in #1024. Other than that, the test looks good to me.

The only problem I see is that it is a bit slow, but this seems to be related to qibojit, so I'd prefer to open an issue instead of blocking this PR.

**Pull request merged**
