### PR TITLE
Hyperoptimizing with Optuna

### PR DESCRIPTION
**Pull request by MatteoRobbiati**
Moving from [Hyperopt](https://github.com/hyperopt/hyperopt) to [Optuna](https://github.com/optuna/optuna), which is more maintained.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

### CODE REVIEW

**Comment by andrea-pasquale** [comment]
Thanks @MatteoRobbiati, given that #1269 was just merged probably we need to update this PR.
Eventually me or @Sam-XiaoyueLi could take care of merging main. Let me know.

**Comment by MatteoRobbiati** [comment]
The coverage here suffers of the same problem we are fixing in #1438. What concerns Hyperopt -> Optuna should be ready to be reviewed @andrea-pasquale @Edoardo-Pedicillo @Sam-XiaoyueLi.

**Review by Edoardo-Pedicillo — APPROVED** [review]

**Comment by scarrazza** [comment]
@MatteoRobbiati could you please fix the conflict?

**Comment by MatteoRobbiati** [comment]
> @MatteoRobbiati could you please fix the conflict?

Done!

**Review by scarrazza — APPROVED** [review]

**Pull request merged**
