### PR TITLE
unvectorization function

### PR DESCRIPTION
**Pull request by renatomello**
Checklist:
- [ ] Reviewers confirm new code works as expected.
- [x] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.

### CODE REVIEW

**Comment by renatomello** [comment]
Closes #743

**Comment by renatomello** [comment]
This closes #738 . I generalized the `vectorization` function to include row- and column-wise vectorization, and created an `unvectorization` function for these two methods. For now, system-wise vectorization is throwing an `NotImplementedError`.

**Review by vodovozovaliza — APPROVED** [review]

**Comment by renatomello** [comment]
> This closes #738 . I generalized the `vectorization` function to include row- and column-wise vectorization, and created an `unvectorization` function for these two methods. For now, system-wise unvectorization is raising `NotImplementedError`.

Now there's an implementation of `unvectorization(order="system")` thanks to Raghav.

**Comment by scarrazza** [comment]
@renatomello thank you, looks good to me. @stavros11 could you please double check before we merge?

**Review by stavros11 — APPROVED** [review]
> @renatomello thank you, looks good to me. @stavros11 could you please double check before we merge?

Yes, looks good to me and tests are passing including GPU. I think we can merge, thanks.

**Pull request merged**
