### PR TITLE
Adjusting clifford condition in GPI2

### PR DESCRIPTION
**Pull request by MatteoRobbiati**
Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

### CODE REVIEW

**Review by AlejandroSopena — APPROVED** [review]

**Review by BrunoLiegiBastonLiegi — APPROVED** [review]

**Comment by renatomello** [comment]
Before merging this: did anyone check if the `GPI2` is actually a Clifford in those parameters?

**Review by renatomello — CHANGES_REQUESTED** [review]
Before merging: did anyone check if the `GPI2` is actually a Clifford in those parameters?

**Comment by AlejandroSopena** [comment]
Yes, it is because $GPI2(0)=\sigma_x$, $GPI2(\pi/2)=\sigma_y$, $GPI2(\pi)=-\sigma_x$ and  $GPI2(3\pi/2)=-\sigma_y$, where $\sigma_j$ are the Pauli matrices.

**Comment by renatomello** [comment]
> Yes, it is because GPI2(0)=σx, GPI2(π/2)=σy, GPI2(π)=−σx and GPI2(3π/2)=−σy, where σj are the Pauli matrices.

I don't see it from the $GPI2$ matrix representation.

**Comment by alecandido** [comment]
That's an error: GPI2 is always a rotation by $\pi/2$, not $\pi$. So, they are square roots of Pauli's.

E.g., cf. https://ionq.com/docs/getting-started-with-native-gates#gpi2

**Comment by AlejandroSopena** [comment]
In the previous code I was printing `gate` instead of `gate1`. Now it can be seen that it maps paulis to paulis up to phases.

**Review by renatomello — APPROVED** [review]

**Comment by alecandido** [comment]
@AlejandroSopena of course, my comment was referred not to the one directly above, but to the previous one, i.e. https://github.com/qiboteam/qibo/pull/1399#issuecomment-2255730701

**Pull request merged**
