### PR TITLE
Docs makeup

### PR DESCRIPTION
**Pull request by MatteoRobbiati**
1. Images in SVG format;
2. Ubuntu font as default (to check if this works for different OS) and remover purple links.

If you are not ok with 2., I can come back to the previous configuration (if yes, I will do the same in the other repos).

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [ ] Documentation is updated.

### CODE REVIEW

**Comment by scarrazza** [comment]
Thanks @MatteoRobbiati. However the logo on the left side bar has disappeared.
Frankly, I would not change the font or color, could you please revert those changes and just keep the svg?

**Comment by MatteoRobbiati** [comment]
> Frankly, I would not change the font or color, could you please revert those changes and just keep the svg?

Yes sure.

**Comment by scarrazza** [comment]
Great @MatteoRobbiati, I understand why all these pictures are so big, are you sure this is the best compression we can achieve? If I try to open the page, I see that the loading of the image takes few seconds...

**Comment by scarrazza** [comment]
Never mind, it was just temporary issue of my browser.

**Pull request merged**
