### PR TITLE
Change `.matrix` from property to method and remove `asmatrix` method

### PR DESCRIPTION
**Pull request by renatomello**
Checklist:
- [ ] Reviewers confirm new code works as expected.
- [x] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.

### CODE REVIEW

**Comment by vodovozovaliza** [comment]
Thank you @renatomello, I think `backend` should also be optional in these functions: 
https://github.com/qiboteam/qibo/blob/5e7357f3779f753fb9011a9f2100ef01df175fc1/src/qibo/gates/abstract.py#L318-L321
https://github.com/qiboteam/qibo/blob/5e7357f3779f753fb9011a9f2100ef01df175fc1/src/qibo/gates/measurements.py#L158-L162
https://github.com/qiboteam/qibo/blob/5e7357f3779f753fb9011a9f2100ef01df175fc1/src/qibo/gates/special.py#L98-L99

**Comment by renatomello** [comment]
@vodovozovaliza thanks. Changed in the `FusedGate` class. I don't think the other two need to be changed, since they are only raising errors anyways.

**Review by vodovozovaliza — APPROVED** [review]

**Review by stavros11 — COMMENTED** [review]
The initial idea was to use the `.matrix` property defined in 

https://github.com/qiboteam/qibo/blob/0539b0d54e811d6fc1c889b5aae177b7d2713f2d/src/qibo/gates/abstract.py#L310

if you want to use the default `GlobalBackend` and `asmatrix` only if you need to use a specific backend, that's why it didn't have a default. But either way is fine with me. If you keep the default in `asmatrix`, you can reduce minor code repetition by changing the property to just
```py
@property
def matrix(self):
    return self.asmatrix()
```

> @vodovozovaliza thanks. Changed in the `FusedGate` class. I don't think the other two need to be changed, since they are only raising errors anyways.

I think it matters for the type of error. Now if someone calls `asmatrix` without argument in these gates they will get a Python argument missing error, instead of our `NotImplementedError`. If you decide to have a default it is better to put it everywhere so that the interface is common.

**Comment by renatomello** [comment]
> The initial idea was to use the `.matrix` property defined in
> 
> https://github.com/qiboteam/qibo/blob/0539b0d54e811d6fc1c889b5aae177b7d2713f2d/src/qibo/gates/abstract.py#L310
> 
> if you want to use the default `GlobalBackend` and `asmatrix` only if you need to use a specific backend, that's why it didn't have a default. But either way is fine with me. If you keep the default in `asmatrix`, you can reduce minor code repetition by changing the property to just
> 
> ```python
> @property
> def matrix(self):
>     return self.asmatrix()
> ```

Right now, we have a redundancy in having a `gate.matrix` property and `gate.asmatrix` method. Then, I'd like to suggest either keeping the former or the latter. Either one is fine by me. Right now, it seems that the best option is to make `gate.matrix` a method and remove `gate.asmatrix` entirely. What do you think?

**Comment by stavros11** [comment]
> Right now, we have a redundancy in having a `gate.matrix` property and `gate.asmatrix` method. Then, I'd like to suggest either keeping the former or the latter. Either one is fine by me. Right now, it seems that the best option is to make `gate.matrix` a method and remove `gate.asmatrix` entirely. What do you think?

Yes, you are right about the redudancy. We have this because `asmatrix` was needed for executing circuits on different backends when we made `Gate` objects backend agnostic and the `matrix` property existed before, so I didn't want to break the interface. Changing `matrix` to a function (with a `backend=None` default argument) and removing `asmatrix` is okay in terms of the backends, however it may break code of external users, ie. they would have to change `.matrix` to `.matrix()`. The main issue is that I think this particular property is used by several people.

**Comment by stavros11** [comment]
> We could do something like we did with the noise channel initialisations and keep the deprecated functionality still working for one or two months while raising warnings letting them know the functionality is deprecated.

This is fine with me. If it is not urgent I would just wait to discuss it in some qibo meeting, or at least ask if @scarrazza agrees. It is not really blocking this PR anyway.

If we do the warning, note that in this case we need to raise it in the property, without changing it to a function. If we change to a function, then people who are doing `gate.matrix` will get a reference to the function (instead of the matrix array) and will not see any warning.

**Comment by scarrazza** [comment]
@renatomello @stavros11 if raising an warning is complex from a dev. point of view, I would suggest going directly to the"breaking change" given that we are releasing 0.2.0 soon.

**Comment by scarrazza** [comment]
@renatomello could you please perform the change, remove the old interface and add a note in the sphinx documentation, explaining that from 0.2.0 the user should use the attribute instead of function.

**Comment by renatomello** [comment]
@scarrazza this is ready for review. Tests depend on https://github.com/qiboteam/qibojit/pull/137/ and vice-versa.

**Review by stavros11 — APPROVED** [review]
Thanks @renatomello, looks good to me.

**Review by scarrazza — APPROVED** [review]

**Pull request merged**
