### PR TITLE
Update backends and ecosystem diagrams in the docs

### PR DESCRIPTION
**Pull request by MatteoRobbiati**
Checklist:
- [ ] Reviewers confirm new code works as expected.
- [x] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.

### CODE REVIEW

**Review by renatomello — COMMENTED** [review]
`Quantum Information` is not aligned with its box

**Comment by MatteoRobbiati** [comment]
> `Quantum Information` is not aligned with its box

You mean it is not centred?

**Comment by renatomello** [comment]
> > `Quantum Information` is not aligned with its box
> 
> You mean it is not centred?

`Information` is out of the box, it doesn't fit

**Comment by MatteoRobbiati** [comment]
> > > `Quantum Information` is not aligned with its box
> > 
> > 
> > You mean it is not centred?
> 
> `Information` is out of the box, it doesn't fit

Could you please check now? It was a problem only in some browsers and I didn't noticed before your comment. Now in my Firefox is fixed.

**Review by renatomello — APPROVED** [review]

**Review by Simone-Bordoni — APPROVED** [review]

**Pull request merged**
