### PR TITLE
Renaming backend methods related to vector and matrix norms

### LINKED ISSUE #1518: Rename backend methods related to norms
Since often the methods `Backend.calculate_norm` and `Backend.calculate_norm_density_matrix` are used to calculate the norms of objects that have the same shape as quantum states but are not exactly quantum states, I suggest renaming these methods, respectively, as `Backend.calculate_vector_norm` and Backend.calculate_matrix_norm` to avoid any misconceptions, especially in the documentations.

### PR DESCRIPTION
**Pull request by renatomello**
Closes #1518 

Checklist:
- [x] Reviewers confirm new code works as expected.
- [x] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.

### CODE REVIEW

**Comment by renatomello** [comment]
@MatteoRobbiati @BrunoLiegiBastonLiegi do you know what is this error in the tests regarding importing `tensorflow` from `qiboml`?

https://github.com/qiboteam/qibo/actions/runs/11794483631/job/32852177151?pr=1520

**Comment by BrunoLiegiBastonLiegi** [comment]
Mmmh weird, but the tests  under tensorflow are still running?

**Comment by MatteoRobbiati** [comment]
I think what is strange is that it didn't fail before: tensorflow is no more a dependency, thus shouldn't [this line](https://github.com/qiboteam/qibo/blob/eedc6095f7fdf9d669c4b403ce2bdbc07a4d5a48/tests/test_backends.py#L116) always set `tensorflow` to False?

**Comment by renatomello** [comment]
It was like that before and it was passing on Windows and Mac but failing
on Ubuntu.

**Comment by MatteoRobbiati** [comment]
> It was like that before and it was passing on Windows and Mac but failing on Ubuntu.

I think because, for some reason, `tensorflow` is still a dependence here: [see pyproject.toml](https://github.com/qiboteam/qibo/blob/ba26163cf56d26e453c5ca27a26f7f5d6fb3b848/pyproject.toml#L72). It has to be removed.

**Review by MatteoRobbiati — APPROVED** [review]
Thanks!

**Review by stavros11 — APPROVED** [review]

**Comment by renatomello** [comment]
Reminder that this PR needs merge coordination with the equivalent `qibojit` PR.

**Comment by MatteoRobbiati** [comment]
> Reminder that this PR needs merge coordination with the equivalent `qibojit` PR.

Do you need reviewers in Qibojit?

**Comment by renatomello** [comment]
> Reminder that this PR needs merge coordination with the equivalent `qibojit` PR.

Not needed after all, so I'm merging this PR.

**Pull request merged**
