### PR TITLE
Generalize `quantum_info.random_clifford` to `n` qubits

### PR DESCRIPTION
**Pull request by renatomello**
Checklist:
- [x] Reviewers confirm new code works as expected.
- [x] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.

### CODE REVIEW

**Comment by renatomello** [comment]
@igres26 @vodovozovaliza @wilkensJ @stavros11 this is ready for review

**Review by vodovozovaliza — APPROVED** [review]
Thank you @renatomello, everything looks good to me

**Comment by renatomello** [comment]
@igres26 @wilkensJ we noticed that we do not need a flag to fuse single-qubit gates, since the class `qibo.models.Circuit` already has a `.fuse()` method.

**Comment by renatomello** [comment]
> @igres26 @wilkensJ: @vodovozovaliza and I noticed that we do not need a flag to fuse single-qubit gates, since the class `qibo.models.Circuit` already has a `.fuse()` method.

```python3
clifford = random_clifford(1).fuse()
```

already does the trick.

**Comment by renatomello** [comment]
@wilkensJ @vodovozovaliza @igres26 @stavros11 there's also another peculiarity that I forgot to mention during the meeting: the algorithm generates circuits with both `CZ`s and `CNOT`s. Do we force the conversion of one into the other? If yes, which one? Or do we leave as is?

**Review by stavros11 — APPROVED** [review]
Thanks for this, looks good to me.

> @igres26 @wilkensJ: @vodovozovaliza and I noticed that we do not need a flag to fuse single-qubit gates, since the class `qibo.models.Circuit` already has a `.fuse()` method. So,
> 
> ```python
> clifford = random_clifford(1).fuse()
> ```
> 
> already does the trick.

Just a note, if the circuit has more than one qubit, I think `fuse()` will fuse up to two-qubit gates by default. You can still do `.fuse(max_qubits=1)` to fuse only single-qubit gates.

> @wilkensJ @vodovozovaliza @igres26 @stavros11 there's also another peculiarity that I forgot to mention during the meeting: the algorithm generates circuits with both `CZ`s and `CNOT`s. Do we force the conversion of one into the other? If yes, which one? Or do we leave as is?

Personally, I have no preference, as I am not sure what will be the application of this. If the goal is to execute these circuits on hardware, as far as I know, all TII hardware uses CZ as the native two-qubit gate. But even if you have CNOTs, the transpiler in qibolab will automatically convert them to CZ before executing. If you want to disable the transpiler and manually create circuits that only have native gates, then you may need to convert everything to CZ as you say.

**Comment by renatomello** [comment]
> Just a note, if the circuit has more than one qubit, I think `fuse()` will fuse up to two-qubit gates by default. You can still do `.fuse(max_qubits=1)` to fuse only single-qubit gates.

The idea was to have a flag to merge single-qubit gates when sampling single-qubit random Cliffords anyways, so the `fuse`method as is still does the job.

> Personally, I have no preference, as I am not sure what will be the application of this. If the goal is to execute these circuits on hardware, as far as I know, all TII hardware uses CZ as the native two-qubit gate. But even if you have CNOTs, the transpiler in qibolab will automatically convert them to CZ before executing. If you want to disable the transpiler and manually create circuits that only have native gates, then you may need to convert everything to CZ as you say.

I'm gonna merge this PR, but still wanna hear about other people's opinions one this, In any case, if any changes are needed, we can put it in another PR.

**Pull request merged**
