### PR TITLE
Fix and speed-up DBI tests

### PR DESCRIPTION
**Pull request by andrea-pasquale**
Now DBI tests are much faster and the implementation is GPU compatible.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [x] Tests are passing.
- [x] Coverage does not decrease.
- [x] Documentation is updated.

### CODE REVIEW

**Review by renatomello — APPROVED** [review]

**Comment by renatomello** [comment]
Maybe this is out of the scope of this PR, but the `generate_Z_operators` and `str_to_symbolic` in `qibo.models.dbi.utils` can be replaced by this faster implementation below:

```python
from functools import reduce
from itertools import product

import numpy as np

from qibo import matrices
from qibo.models.dbi.utils import generate_Z_operators

def generate_Z_operators_new(nqubits):
    combination_strings = list(product(["I", "Z"], repeat=nqubits))[1:]

    dictionary = {}
    dictionary["I"*nqubits] = np.eye(2**nqubits, dtype=complex)
    for string in combination_strings:
        matrix = [getattr(matrices, s) for s in string]
        matrix = reduce(np.kron, matrix)
        dictionary["".join(string)] = matrix
        del matrix  # maybe this is needed to control memory usage for nqubits >= 7-ish

    return dictionary

nqubits = 2
%timeit generate_Z_operators(nqubits)
%timeit generate_Z_operators_new(nqubits)

nqubits = 5
%timeit generate_Z_operators(nqubits)
%timeit generate_Z_operators_new(nqubits)
```

This is in line of how `qibo.quantum_info.basis.pauli_basis` is implemented, and it might even be added to it using the `pauli_order` argument.
However, even though this is faster than the current implementation in `dbi, it is still inefficient overall for a number of qubits greater than 7-ish. I had a conversation with @BrunoLiegiBastonLiegi about rewriting the `pauli_basis` function in a way that returns a generator instead of all these big matrices, so this might be even one more reason to do it.

**Comment by marekgluza** [comment]
> Maybe this is out of the scope of this PR, but the `generate_Z_operators` and `str_to_symbolic` in `qibo.models.dbi.utils` can be replaced by this faster implementation below:
> 
> ```python
> from functools import reduce
> from itertools import product
> 
> import numpy as np
> 
> from qibo import matrices
> from qibo.models.dbi.utils import generate_Z_operators
> 
> def generate_Z_operators_new(nqubits):
>     combination_strings = list(product(["I", "Z"], repeat=nqubits))[1:]
> 
>     dictionary = {}
>     dictionary["I"*nqubits] = np.eye(2**nqubits, dtype=complex)
>     for string in combination_strings:
>         matrix = [getattr(matrices, s) for s in string]
>         matrix = reduce(np.kron, matrix)
>         dictionary["".join(string)] = matrix
>         del matrix  # maybe this is needed to control memory usage for nqubits >= 7-ish
> 
>     return dictionary
> 
> nqubits = 2
> %timeit generate_Z_operators(nqubits)
> %timeit generate_Z_operators_new(nqubits)
> 
> nqubits = 5
> %timeit generate_Z_operators(nqubits)
> %timeit generate_Z_operators_new(nqubits)
> ```
> 
> This is in line of how `qibo.quantum_info.basis.pauli_basis` is implemented, and it might even be added to it using the `pauli_order` argument. However, even though this is faster than the current implementation in `dbi`, it is still inefficient overall for a number of qubits greater than 7-ish. I had a conversation with @BrunoLiegiBastonLiegi about rewriting the `pauli_basis` function in a way that returns a generator instead of all these big matrices, so this might be even one more reason to do it.

@Sam-XiaoyueLi please have a look

Thank you @renatomello for the useful suggestion!

**Comment by renatomello** [comment]
@MatteoRobbiati may I ask you to review this soon because #1202 depends on it? Thanks.

**Review by MatteoRobbiati — APPROVED** [review]
Thanks @andrea-pasquale for the fix and @renatomello for the reminder.

**Pull request merged**
