### PR TITLE
Remove custom backend classes

### PR DESCRIPTION
**Pull request by stavros11**
Following what is discussed in #499, this PR removes the `TensorflowCustomBackend` and `JITCustomBackend` classes from qibo. These classes will be moved to the qibotf and qibojit repositories respectively.

TODO:
- [x] Complete migration to qibojit. Implemented in qiboteam/qibojit#35.
- [x] Complete migration to qibotf. Implemented in qiboteam/qibotf#12
- [x] Move any hard-coded regressions, for example these that are found in tests based on random number instances, to the respective backends. @mlazzarin this should simplify the ROCm testing issues once fixed.
- [ ] (?) Find a way for CI to work before releasing.

The general goal of this is to enable making changes in the backends without having to touch the qibo code, so any other simplification contributes to this should be considered here.

### CODE REVIEW

**Comment by stavros11** [comment]
Following our discussion with @scarrazza, in order to make CI work for qiboteam/qibojit#35 we should make a pre-release from this branch. I believe this PR is ready from the qibo side, so we could use this for pre-release and check if CI will work in the other repository.

In order to test this locally, please start with a clean environment, install the following:
1. qibo from `rmbackends` branch.
2. qibojit from `backendcls` branch (qiboteam/qibojit#35)
3. qibotf from `backendcls` branch (qiboteam/qibotf#12)

and execute all the tests on these three repositories. In my local machine all tests work on both CPU and GPU.

**Comment by mlazzarin** [comment]
I think that we need to change this line.

https://github.com/qiboteam/qibo/blob/e21e0074194219561fc164c5e424fa671e3f7d9d/examples/benchmarks/main.py#L181

**Comment by stavros11** [comment]
> I think that we need to change this line.
> 
> https://github.com/qiboteam/qibo/blob/e21e0074194219561fc164c5e424fa671e3f7d9d/examples/benchmarks/main.py#L181

Thanks for catching this, I forgot to run the example tests before. It should be okay now.

**Review by mlazzarin — APPROVED** [review]
Looks good to me. All tests are ok on my setup (apart from #502).

**Comment by scarrazza** [comment]
@stavros11 thanks for this, I think we could create pre-releases for qibojit and qibotf and then test them here.

**Comment by stavros11** [comment]
> @stavros11 thanks for this, I think we could create pre-releases for qibojit and qibotf and then test them here.

That also works. In the meantime we can temporarily clone qibo from this branch in the CI of qibojit and qibotf, as I do [here](https://github.com/qiboteam/qibojit/blob/a4730a04db23aa56892a18c775bbc1df69d773c7/.github/workflows/rules.yml#L24), to make sure that everything is ok before releasing them. Once qibo 0.1.7 is released we can change the rules to install qibo from pip again.

**Comment by scarrazza** [comment]
@stavros11 this should be ready for testing.
I have tried quickly but it crashes, see https://github.com/qiboteam/qibo/actions/runs/1425472067

**Comment by stavros11** [comment]
> @stavros11 this should be ready for testing. I have tried quickly but it crashes, see https://github.com/qiboteam/qibo/actions/runs/1425472067

I changed the rules to install qibojit and qibotf from pre-release and everything seems to work now. This and #499 should be good to go.

**Review by scarrazza — APPROVED** [review]
@stavros11 thank you. Looks good to me!

**Pull request merged**
