### PR TITLE
Copy ground state before passing to adiabatic evolution

### LINKED ISSUE #824: The adiabatic evolution model alters the h0 object when using symbolic hamiltonians
It seems like the `AdiabaticEvolution` model replaces things on the initial Hamiltonian, making repeated adiabatic evolutions without re-defining this initial Hamiltonian fail. 

This should reproduce the issue:

```python

import numpy as np
from qibo import hamiltonians
from qibo.models.evolution import AdiabaticEvolution

nqubits = 5

h_x = hamiltonians.X(nqubits, dense=False)
print(h_x.ground_state())

h_ising = hamiltonians.TFIM(nqubits, h=1.0, dense=False)
print(h_ising.ground_state())

s = lambda t: t
evolve = AdiabaticEvolution(h_x, h_ising, s, dt=0.01, solver='exp')
final_state = evolve(final_time=10)
print(final_state)

print(h_x.ground_state()) #<--- This is now changed!
print(h_ising.ground_state())

evolve = AdiabaticEvolution(h_x, h_ising, s, dt=0.01, solver='exp')
final_state = evolve(final_time=10)
print(final_state) #<--- This has now changed too then!

```

You will notice how the h_x has changed.

This is not the case with `dense=True` Hamiltonians.

Why does this happen? Should this be fixed, or just properly documented?

### PR DESCRIPTION
**Pull request by stavros11**
Fixes #824. @MatteoRobbiati indeed you are right, it is a qibojit issue.

Checklist:
- [ ] Reviewers confirm new code works as expected.
- [ ] Tests are passing.
- [ ] Coverage does not decrease.
- [x] Documentation is updated.

### CODE REVIEW

**Review by scarrazza — APPROVED** [review]
Good point, thanks.

**Comment by scarrazza** [comment]
@MatteoRobbiati please let us know if this works also for you.

**Review by MatteoRobbiati — APPROVED** [review]
I confirm it works as expected also using the `qibojit` backend.
Thank you @stavros11!

**Comment by MatteoRobbiati** [comment]
Only to be sure it is a problem of mine: is it normal that the execution time of the #824 code requires 1sec using `numpy` and 2min using `qibojit`?

**Comment by stavros11** [comment]
> Only to be sure it is a problem of mine: is it normal that the execution time of the #824 code requires 1sec using `numpy` and 2min using `qibojit` @stavros11?

With @andrea-pasquale we have observed this issue in the past for the `NumbaBackend`, see for example 
https://github.com/qiboteam/qibo/issues/839#issuecomment-1482683282
We suspect something is wrong but we did not investigate. I will try to have a look when I have time. This problem seems to appear only with numba, not cupy.

**Comment by MatteoRobbiati** [comment]
> > Only to be sure it is a problem of mine: is it normal that the execution time of the #824 code requires 1sec using `numpy` and 2min using `qibojit` @stavros11?
> 
> With @andrea-pasquale we have observed this issue in the past for the `NumbaBackend`, see for example [#839 (comment)](https://github.com/qiboteam/qibo/issues/839#issuecomment-1482683282) We suspect something is wrong but we did not investigate. I will try to have a look when I have time. This problem seems to appear only with numba, not cupy.

Ok perfect. I will have a look too with some `python` profiler.

**Pull request merged**
